name: Create Release ZIP

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Build ZIP Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r BlackHole-${{ github.ref_name }}.zip . \
          -x ".git/*" \
          -x ".github/*"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: BlackHole ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}

            Repository:
            https://github.com/rezakhosh78/BlackHole
          artifacts: |
            BlackHole-${{ github.ref_name }}.zip
